/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#827470',
        'outline-variant': '#d4c3be',
        'surface-container-highest': '#e2e2e2',
        'primary-fixed': '#ffdbd0',
        'on-background': '#1a1c1c',
        'on-secondary-fixed-variant': '#374952',
        'on-tertiary': '#ffffff',
        background: '#f9f9f8',
        primary: '#442a22',
        'on-tertiary-container': '#bdb3af',
        'surface-tint': '#77574d',
        'on-tertiary-fixed-variant': '#4c4542',
        'on-primary-fixed': '#2c160e',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eeeeed',
        'primary-container': '#5d4037',
        'surface-bright': '#f9f9f8',
        'on-secondary-fixed': '#0a1e26',
        'surface-container-low': '#f4f4f3',
        'on-secondary-container': '#52656f',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#cfc4c0',
        'surface-variant': '#e2e2e2',
        tertiary: '#352f2c',
        error: '#ba1a1a',
        'on-surface-variant': '#504441',
        'secondary-fixed': '#d1e6f0',
        'on-primary-fixed-variant': '#5d4037',
        'tertiary-fixed': '#ece0dc',
        'secondary-fixed-dim': '#b5cad4',
        'on-secondary': '#ffffff',
        secondary: '#4e616a',
        'sky-blue': '#CFD8DC',
        'tertiary-container': '#4c4542',
        'error-container': '#ffdad6',
        'surface-dim': '#dadad9',
        'inverse-surface': '#2f3130',
        'earth-tan': '#BCAAA4',
        'on-tertiary-fixed': '#201a18',
        'inverse-primary': '#e7bdb1',
        'on-surface': '#1a1c1c',
        'glass-border': 'rgba(255, 255, 255, 0.6)',
        'on-primary-container': '#d4ada1',
        'inverse-on-surface': '#f1f1f0',
        'secondary-container': '#cee3ee',
        'primary-fixed-dim': '#e7bdb1',
        surface: '#f9f9f8',
        'on-primary': '#ffffff',
        'surface-container-high': '#e8e8e7',
        'glass-bg': 'rgba(255, 255, 255, 0.4)',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-tablet': '32px',
        'margin-desktop': '64px',
        gutter: '24px',
        'container-max': '1280px',
        unit: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Playfair Display', 'serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-md': [
          '14px',
          { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-lg': [
          '56px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg-mobile': [
          '32px',
          { lineHeight: '1.2', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      animation: {
        'fade-up': 'fadeUp 1.2s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'float-slow': 'floatSlow 6s cubic-bezier(0.45, 0, 0.55, 1) infinite',
        'modal-in': 'modalIn 0.32s cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translate3d(0, 12px, 0)' },
          '50%': { transform: 'translate3d(0, -12px, 0)' },
        },
        modalIn: {
          '0%': { opacity: '0', transform: 'translateY(16px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      boxShadow: {
        glass: '0 20px 40px rgba(0, 0, 0, 0.04)',
        'glass-hover': '0 30px 60px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}
